apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
spec:
  type: {{ .Values.api.service.type }}
  ports:
  - port: {{ .Values.api.service.port }}
    targetPort: 8080
  selector:
    app: {{ .Release.Name }}-api
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-correlator
spec:
  type: {{ .Values.correlator.service.type }}
  ports:
  - port: {{ .Values.correlator.service.port }}
    targetPort: 8080
  selector:
    app: {{ .Release.Name }}-correlator
