global:
  redisConnectionString: garnet:6379

garnet:
  image:
    repository: ghcr.io/microsoft/garnet
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 6379
  persistence:
    enabled: true
    storageClass: ""
    accessMode: ReadWriteOnce
    size: 10Gi

api:
  image:
    repository: synapse-api
    tag: latest
  service:
    type: ClusterIP
    port: 8080
  env:
    SYNAPSE_DASHBOARD_SERVE: true
    SYNAPSE_API_AUTH_TOKEN_FILE: /app/tokens.yaml

operator:
  image:
    repository: synapse-operator
    tag: latest
  service:
    type: ClusterIP
  env:
    SYNAPSE_OPERATOR_RUNNER_API: http://api:8080
    DOCKER_HOST: unix:///var/run/docker.sock

correlator:
  image:
    repository: synapse-correlator
    tag: latest
  service:
    type: ClusterIP
    port: 8081

serviceAccount:
  create: true
  annotations: {}
  name: ""

networkPolicy:
  enabled: false
